// <auto-generated />
using System;
using FixConnect.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixConnect.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504075231_isActive")]
    partial class isActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FixConnect.DAL.Models.Admin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionsLevel")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Customer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LiveInvoiceTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.PortfolioItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Proposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalId"));

                    b.Property<int?>("DurationEstimate")
                        .HasColumnType("int");

                    b.Property<decimal?>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaterialCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ProposalId");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TargetWorkerId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int")
                        .HasAnnotation("Range", new[] { 1, 5 });

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("WorkerId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Worker", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("FixConnect.DAL.Models.WorksAt", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("WorksAt");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Admin", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("FixConnect.DAL.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Customer", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("FixConnect.DAL.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Job", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Proposal", "Proposal")
                        .WithOne("Job")
                        .HasForeignKey("FixConnect.DAL.Models.Job", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.PortfolioItem", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Worker", "Worker")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Proposal", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Request", "Request")
                        .WithMany("Proposals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Customer", "Customer")
                        .WithMany("Proposals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Worker", "Worker")
                        .WithMany("Proposals")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Request");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Request", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Region", "Region")
                        .WithMany("Requests")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Worker", "TargetWorker")
                        .WithMany("TargetedRequests")
                        .HasForeignKey("TargetWorkerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FixConnect.DAL.Models.Customer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Region");

                    b.Navigation("TargetWorker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Review", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Job", "Job")
                        .WithOne("Review")
                        .HasForeignKey("FixConnect.DAL.Models.Review", "JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Worker", "Worker")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Job");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Transaction", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Wallet", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Worker", "Worker")
                        .WithOne("Wallet")
                        .HasForeignKey("FixConnect.DAL.Models.Wallet", "WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Worker", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("FixConnect.DAL.Models.Worker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.WorksAt", b =>
                {
                    b.HasOne("FixConnect.DAL.Models.Region", "Region")
                        .WithMany("WorksAt")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixConnect.DAL.Models.Worker", "Worker")
                        .WithMany("WorksAt")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Customer", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("Requests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Job", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Proposal", b =>
                {
                    b.Navigation("Job");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Region", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("WorksAt");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Request", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FixConnect.DAL.Models.Worker", b =>
                {
                    b.Navigation("PortfolioItems");

                    b.Navigation("Proposals");

                    b.Navigation("Reviews");

                    b.Navigation("TargetedRequests");

                    b.Navigation("Wallet");

                    b.Navigation("WorksAt");
                });
#pragma warning restore 612, 618
        }
    }
}
